import { Metadata } from "next";
import { Nanum_Pen_Script, Anton } from "next/font/google";
import localFont from "next/font/local";

export const jeju = localFont({
  src: [
    {
      path: "../assets/fonts/doldam.woff2",
    },
    {
      path: "../assets/fonts/doldam.woff",
    },
  ],
});
export const nanumPenScript = Nanum_Pen_Script({
  weight: "400",
  preload: false,
});

export const anton = Anton({ weight: "400" });

export const metadata: Metadata = {
  title: {
    template: "%s | SU",
    default: "수코딩 | 누구나 쉽게 배우는 코딩 교육",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  );
}
