import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { Metadata } from "next";
import { Suspense } from "react";

// export const metadata: Metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export function generateMetadata(): Metadata {
  // 비동기 통신의 결과를 메타데이터의 정보로 활용할 수 있다.
  return {
    title: "Next.js",
    description: "Generated by Next.js",
  };
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // 데이터 패칭
  return (
    <html lang="ko">
      <body>
        <Suspense fallback={<h1>Header Loading</h1>}>
          <Header />
        </Suspense>
        {children}
        <Footer />
      </body>
    </html>
  );
}
