import Footer from "@/components/common/Footer";
import Header from "../components/common/Header";
import "@/assets/css/index.css";
import RealtimeProvider from "@/components/common/RealtimeProvider"; // 💡 [추가]
import { createClient } from "@/utils/supabase/server"; // 💡 [추가]

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({ // 💡 [수정] async 추가
  children,
}: {
  children: React.ReactNode;
}) {
  // 💡 [추가] 레이아웃(서버)에서 사용자 정보를 가져옵니다.
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang="ko">
      <body>
        {/* 💡 [수정] RealtimeProvider로 감싸고 userId를 전달합니다. */}
        <RealtimeProvider userId={user?.id}>
          <div className="min-h-screen bg-gray-950 text-gray-100">
            <Header />
            <main className="max-w-6xl mx-auto px-4 py-8">{children}</main>
            <Footer />
          </div>
        </RealtimeProvider>
      </body>
    </html>
  );
}